Creation of the toolbar section
malodev1234/Portfolio_setup_mobile_first pull request #2
Opened 2023-03-25 07:08 UTC by malodev1234

- I created a main section having class name screen_containe
- I created  inside screen_container **two children** 
- I create the first child of screen_container named  header
- I create the second child of screen_container name  main
- I add  one section in side header contains one paragraph tag and img tags and theirs value
- I add two children inside main tag
- I add  the first section named main_container which contains  two **paragraphe** tags and one **heading** tag
- I add the second child named  icons-container  which contains a div container and img 
- I add inside div container fives images for icons

2023-03-25 09:03 UTC, Tufahel requested changes
Hi @malodev1234 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, but all linter tests are not passed successfully.

As a successfully integrated linter test is one of the major requirements of every project, so I am invalidating this review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-30 07:49 UTC, LionRouge1 requested changes
Hi @malodev1234, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job implementing the design it looks identic to Figma's design :1st_place_medal: 
- Nice work using HTML & CSS best practices :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 07:49 UTC, LionRouge1 commented on index.html
> +					<p class="Title_logo">My Logo</p>
- [ ] Please use `a` tag for your logo. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

- [ ] Kindly move the logo outside of the `nav` tag. `nav` tag it uses to wrap navigation links on the webpage.

2023-03-30 07:49 UTC, LionRouge1 commented on index.html
> +					<img src="./images/i.png"  class="logo" alt="Icon menu">
- [ ] Nice work wrapping the hamburger button image with `nav` tag :clap: However what do you think about using this structure for the Toolbar:
```sh
<header class="toolbar_container">
  <a href="#" class="Title_logo">My Logo</a>
  <nav>
    <img src="./images/i.png"  class="logo" alt="Icon menu">
  </nav>
</header>
```
It is now cleaner, isn't it? :sunglasses:

2023-03-30 07:49 UTC, LionRouge1 commented on index.html
> +				<p class="paragraphe">Hey There. <br/>I’m Leader.</p>
- [ ] Please use `h1` tag for your name. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-03-30 07:49 UTC, LionRouge1 commented on index.html
> +					<img  class="ilustration" src="./images/Illustration.png" alt="images">
- [ ] Since this image is part of the decorations, kindly use CSS background-image instead of `img` tags for aesthetic reasons. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.[Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

2023-03-30 07:49 UTC, LionRouge1 commented on index.html
> +				</div>
- [ ] Please use a `ul` tag to group the media icons, `li` tag to wrap each icon, and each icon has a link `a` tag. Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href` attribute.

2023-03-30 09:36 UTC, LionRouge1 approved these changes
Hi @malodev1234, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-07-18 17:36 UTC, merged